### ISSUE TITLE
This site can’t provide a secure connection

### ISSUE THREAD

**Issue by Axolyz** [gaowanliang/googleTranslatorKusaMaker#1]
# 错误信息
浏览器：
This site can’t provide a secure connection
127.0.0.1 sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR
命令行：
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 291-097-895
 * Running on http://0.0.0.0:4586/ (Press CTRL+C to quit)
127.0.0.1 - - [18/Aug/2020 19:03:02] code 400, message Bad request version ('úú\
x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00
\x01\x93êê\x00\x00\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')
127.0.0.1 - - [18/Aug/2020 19:03:02] "[35m[1m

# 环境
python 3.8.2 32bit
chrome Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by gaowanliang** [comment]
这个问题应该是不影响使用的，我公开版本带有谷歌的reCAPTCHA验证，部署到本地就不需要了，但是我前端引用的JS没有删除，刚才已经删掉了相关代码了
